server:
  port: 8081

spring:
  application:
    name: ms-pacientes

  datasource:
    # Usamos las variables de entorno de Docker si existen, o localhost si lo corres desde tu IDE
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rednorte_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Cambiamos a 'update' para que tus datos no se borren cada vez que reinicias
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true