version: '3.8'

services:

  # ==========================================
  # --- BASES DE DATOS ---
  # ==========================================
  postgres-pacientes:
    image: postgres:15-alpine
    container_name: postgres-pacientes
    environment:
      POSTGRES_DB: pacientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Puerto estándar de Postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pacientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-lista-espera:
    image: postgres:15-alpine
    container_name: postgres-lista-espera
    environment:
      POSTGRES_DB: listas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Mapeado al 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d listas_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # NUEVA BD: Para aislar los usuarios y credenciales
  postgres-security:
    image: postgres:15-alpine
    container_name: postgres-security
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432" # Mapeado al 5435 para no chocar con las otras
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d security_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  # ==========================================
  # --- MICROSERVICIOS CORE ---
  # ==========================================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

      # ==========================================
      # --- BFF (Backend For Frontend) ---
      # ==========================================
  bff:
    build: ./bff
    container_name: bff
    ports:
      - "8090:8090" # Puerto definido en tu bff/application.yml
    environment:
      SERVER_PORT: 8090
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # NUEVO MICROSERVICIO: Emisor de Tokens
  security:
    build: ./security
    container_name: security
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      EUREKA_URL: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-security:5432/security_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} # Inyectado desde el archivo .env
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-security:
        condition: service_healthy
    restart: unless-stopped

  ms-pacientes:
    build: ./ms-pacientes
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      EUREKA_URL: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-pacientes:5432/pacientes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} # Para que pueda validar los tokens
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-pacientes:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  ms-lista-espera:
    build: ./ms-lista-espera
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      EUREKA_URL: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-lista-espera:5432/listas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} # Para que pueda validar los tokens
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-lista-espera:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # ==========================================
  # --- GATEWAY ---
  # ==========================================
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server