server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # CORRECCIÓN DE ESTRUCTURA: globalcors y routes van directo bajo gateway
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ruta-pacientes
          uri: lb://ms-pacientes
          predicates:
            - Path=/api/pacientes/**

        - id: ruta-lista-espera
          uri: lb://ms-lista-espera
          predicates:
            - Path=/api/listas-espera/**

        - id: ruta-bff
          uri: lb://bff
          predicates:
            - Path=/bff/**

        - id: security-route
          uri: lb://security  # <-- Ahora apunta a tu nuevo nombre
          predicates:
            - Path=/api/auth/**  # (O la ruta que hayas definido para el login/registro)

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/