server:
  port: 8080
  # 🟢 ESTO ES OBLIGATORIO: Evita que el navegador intente conectar a los IDs de los contenedores Docker
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ruta-security
          uri: lb://security
          predicates:
            - Path=/api/auth/**

        - id: ruta-bff
          uri: lb://bff
          predicates:
            - Path=/bff/auth/**, /api/bff/**

        - id: ruta-pacientes
          uri: lb://ms-pacientes
          predicates:
            - Path=/api/pacientes/**

        - id: ruta-doctores
          uri: lb://ms-doctores
          predicates:
            - Path=/api/doctores/**

        - id: ms-lista-espera
          uri: lb://ms-lista-espera
          predicates:
            - Path=/api/listas-espera/**

        - id: ms-chatbot
          uri: lb://ms-chatbot
          predicates:
            - Path=/api/chatbot/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}