server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ruta-pacientes
          uri: lb://ms-pacientes
          predicates:
            - Path=/api/pacientes/**

        - id: ms-lista-espera
          uri: lb://ms-lista-espera
          predicates:
            - Path=/api/lista-espera/**

        - id: ruta-bff
          uri: lb://bff
          predicates:
            - Path=/bff/**

        - id: ruta-security
          uri: lb://security
          predicates:
            - Path=/api/auth/**

        - id: ms-chatbot
          uri: lb://ms-chatbot
          predicates:
            - Path=/api/chatbot/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/