apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pacientes
  namespace: rednorte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pacientes
  template:
    metadata:
      labels:
        app: ms-pacientes
    spec:
      containers:
        # Reemplaza con tu cuenta de AWS
        - name: ms-pacientes
          image: 174448597449.dkr.ecr.us-east-1.amazonaws.com/rednorte-ms-pacientes
          env:
            # Aquí apuntamos al servicio de Postgres que creamos
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/rednorte"

            # Estas variables las toma de tu caja fuerte (Secret)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rednorte-secrets
                  key: "SPRING_DATASOURCE_USERNAME"

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rednorte-secrets
                  key: "SPRING_DATASOURCE_PASSWORD"

            # Si tu app usa Eureka, asegúrate de que esto esté configurado
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"

          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-pacientes-svc
  namespace: rednorte
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: ms-pacientes
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-pacientes-hpa
  namespace: rednorte
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-pacientes
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50