server:
  port: 8083

spring:
  application:
    name: security
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/security_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      # Inyectamos EUREKA_URL desde docker-compose, y si no existe (al programar local), usa localhost
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# CRÍTICO: La clave secreta debe ser larga (mínimo 32 caracteres)
jwt:
  secret:
    key: ${JWT_SECRET_KEY}