server:
  port: 8090

spring:
  application:
    name: bff

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# Logging para depurar llamadas Feign
logging:
  level:
    com.example.bff.client: DEBUG